name: Push Backend Image to GAR
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: 'projects/660544013770/locations/global/workloadIdentityPools/gh-pool/providers/provider-github'
          service_account: 'gh-actions@yorisoi.iam.gserviceaccount.com'

      - name: Authorize Docker
        id: docker-auth
        uses: docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: ${{ steps.auth.outputs.access_token }}
          registry: asia-northeast1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: asia-northeast1-docker.pkg.dev/yorisoi/yorisoi-backend/main:latest
          file: ./cloudrun/Dockerfile
          context: ./

      - name: Download Cloud Run Service YAML
        run: |
          gcloud run services describe yorisoi-backend --format yaml --region asia-northeast1 > ./service.yaml

      # replace github_sha field to latest commit sha. Changing spec.template is required to deploy new revision.
      # reference: https://cloud.google.com/run/docs/deploying?hl=ja#revision -- check yaml tab.
      - name: Change some property of service.yaml
        run: |
          sed -i "s/github_sha: .*/github_sha: ${{ github.sha }}/g" ./service.yaml

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: "asia-northeast1"
          metadata: "./service.yaml"
